@startuml
'https://plantuml.com/use-case-diagram
actor Clerk as "Statistician"
rectangle Database
rectangle "World Population" {
usecase UC2 as "Get all people living in cities vs those living outside of cities"
usecase UCb as "Print populations in  cities vs not in cities"

Clerk - UC2
UC2 ..> UCb : include
UC2 - Database
}
@enduml